### ISSUE TITLE
m3u8 playlist imported although the songs in the playlists can't be found.

### ISSUE THREAD

**Issue by qoished** [namidaco/namida-snapshots#1] opened 2024-06-21 06:52 UTC
I don't know whether m3u8 playlist support is properly implemented but I can't play my songs from the playlists. The album art is shown on each song although the song itself isn't playable. Also instead of the song name I see the path file of the songs in the playlist only

**Comment by MSOB7YY** [comment] 2024-06-26 18:26
this means that the path that namida read, points to nothing? can you send a sample file pls

**Comment by qoished** [comment] 2024-06-26 18:57
Yeah @MSOB7YY see the files in my drive [https://drive.google.com/drive/folders/1QCVNtj_ZHEwe5QR8zQjHlTYhUi49LRhq?usp=sharing]. So basically the playlist should have the name "Betrayal" and the other is a screenshot. If after downloading the app I add my playlist folder and let the scan run and finish upon the next time the app runs I receive pop ups that some songs are missing and the app just freezes there and can't proceed any further.
Also on the first boot if I open a playlist I see can see the target file/song of each one of the songs in the playlist and not there name

**Comment by MSOB7YY** [comment] 2024-06-26 19:09
![Screenshot_20240626-210236_Namida](https://github.com/namidaco/namida-snapshots/assets/85245079/1cf4bd9f-12fd-446b-a50e-51c1acacf7c9)
![Screenshot_20240626-210250_Namida](https://github.com/namidaco/namida-snapshots/assets/85245079/5a2211e2-c25e-40f9-ab7c-88300d481dc8)

~~this is how the playlist looks in queue and in playlist tabs (0s bcz nothing exists on my phone), so basically everything is working fine~~

i just noticed that the path extracted is not accurate, apparently this needs improvement 
![Screenshot_20240626-210716_Namida](https://github.com/namidaco/namida-snapshots/assets/85245079/f7de87f4-c8d0-475f-821a-bab62778f8da)

**Comment by MSOB7YY** [comment] 2024-06-26 19:14
about the black screen, it's caused by the dialog at startup. i had to delete latest_queue.json file in order to bypass this 

thank u for reporting, not sure what the real issue is but gonna investigate

**Comment by qoished** [comment] 2024-06-26 19:22
Mine is shown like this![Screenshot_2024-06-26-22-22-34-00_76169158703de17dd8d9d0f5c2b96fc9.jpg](https://github.com/namidaco/namida-snapshots/assets/63118672/2d6651ea-6a5e-42cf-aed7-ee77d306bab4)

**Comment by MSOB7YY** [comment] 2024-06-26 19:33
yeah that's bcz the paths are not extracted properly, i will do a fix soon

**Comment by MSOB7YY** [comment] 2024-07-01 18:20
@qoished both issues are fixed now, thank u so muchhhh for pointing them out <33 https://github.com/namidaco/namida-snapshots/releases

**Closed** 2024-07-01 18:20 UTC
